sudo: true
language: python
python:
  - 2.7
  - 3.5
services:
    - mysql
addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client
before_install:
  - mysql -u root --password="" < test/travis.sql
install: pip install -r requirements.txt
before_script:
  - export SQLALCHEMY_DATABASE_URI='mysql+pymysql://test:test@localhost/testdb'
  - export FLASK_CONFIG=testing
  - export FLASK_APP=run.py
script: python tests.py